# Generated by Django 5.1.3 on 2024-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando pagamento'), ('Processando', 'Processando'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Aguardando', max_length=20),
        ),
    ]
